print('******************************************')
print('              PROGRAM PYTHON')
print('          oleh : Jibril Ibni Jubair')
print('             kelas : X PPLG 2')
print('******************************************')